# 예외처리
프로그램이 실행 중 어떤 원인에 의해서 오작동을 하거나 비정상적으로 종료되는 경우

⇒ 프로그램 에러 또는 오류

  `발생시점에 따라 컴파일 에러와 런타임에러로 나눠짐`

- 컴파일 에러
    - 컴파일 시에 발생하는 에러
- 런타임 에러
    - 실행 시에 발생하는 에러
    - 프로그램 종료
- 논리적 에러
    - 실행은 되지만, 의도와 다르게 동작하는것
    - 프로그램 종료x

> java의 런타임 에러
> 
- 에러(error) : 프로그램 코드에 의해서 수습될 수 없는 `심각한 오류`
- 예외(exception) : 프로그램 코드에 의해서 수습될 수 있는 `미약한 오류`
    
     ***“ 에러는 어쩔 수 없고 예외는 처리하자”*** 
    
- 예외처리의 정의와 목적
    - 정의 : 프로그램 실행 시 발생할 수 있는 예외의 발생에 대비한 코드를 작성하는 것
    - 목적 : 프로그램의 비정상 종료를 막고, 정상적인 실행상태를 유지하는 것

```java
🐳 자바 컴파일러(javac.exe)의 기능 
1. 구문 체크
2. 번역
3. 최적화
	+ 생략된 코드 추가
```
<br>

## 예외 클래스의 계층구조

- 상속 계층도

![image](https://user-images.githubusercontent.com/102898794/199236412-2ad05f60-46cb-46b7-b669-36df0b7c4af6.png)
  - Object : 최고조상
  - Throwable : 클래스 , 모든 오류 조상
  - exception,error→ 런타임 오류

![image](https://user-images.githubusercontent.com/102898794/199236747-ab3d99ed-c097-4eb1-8e89-29bd848c794d.png)
- Exception+자손 클래스 들 : `사용자`의 실수와 같은 외적인 요인에 의해 발생
- Error + 자손 클래스들 : `프로그래머`의 실수로 발생

- 프로그램 오류
    1. 컴파일 에러
    2. 런타임 에러
        1. Error(심각한에러)
        2. Exception(미약한 에러)
            1. Exception와 그 자손들
                - 체크드 예외 (예외처리 필수)
                    - try catch필수
            2. RuntimeException과 그 자손
                - 언체크드 예외(예외처리 선택)
                    - try catch 선택
    3. 논리적 에러
<br>

## 예외처리하는 방법

1. try-catch문(직접처리하기)
2. 예외선언하기(예외떠넘기기, 알리기)
3. 은폐 덮기
    1. 빈 catch
    2. 웬만하면 쓰이지 않지만 빅데이터 사용할때 쓰임
<br>

### 1. try-catch문

*** try-catch문 내에 포함된 문장이 하나뿐이어도 `괄호{} 생략 안됨`

![image](https://user-images.githubusercontent.com/102898794/199236888-6a65a925-5f9f-4fed-82b7-078535d94560.png)

- try-catch문 흐름
    - try블럭 내에서 예외가 발생한 경우,
        1. 발생한 예외와 일치하는 catch 블럭이 있는지 확인
        2. **일치하는 catch블럭을 찾게되면**, 그 catch블럭 내의 문장 수행 후 전체 try-catch문 빠져나가 
        그 다음 문장 계속해서 수행
        but, **일치하는 catch블럭을 찾지 못하면** , 예외는 처리되지 못한다
        ⇒ `프로그램 비정상 종료`
            
            ```java
            public static void main(String args[]) {
            		System.out.println(1);			
            		System.out.println(2);
            		try {
            			System.out.println(3);
            			System.out.println(0/0);// 고의로 ArithmeticException 에러발생!!
            			System.out.println(4); 	// 실행되지 않는다.
            		} catch (ArithmeticException ae)	{
            			if (ae instanceof ArithmeticException) 
            				System.out.println("true");	
            			System.out.println("ArithmeticException");
            		} catch (Exception e){//->ArithmeticException제외 모든 에러 발생
            			System.out.println("Exception");
            		}	// try-catch의 끝
            		System.out.println(6);
            	}	// main메서드의 끝
            ```
            
    - try블럭 내에서 예외가 발생하지않은 경우,
        - catch문 거치지 x, try-catch문 빠져나간다
            
            ```java
            public static void main(String args[]) {
            			System.out.println(1);			
            			try {
            				System.out.println(2);
            				System.out.println(3);
            			} catch (Exception e)    {
            				System.out.println(4);  //실행되지 않는다
            			} // try-catch의 끝
            			System.out.println(5);
            	}
            ```
            

- Exception
    - 모든 예외 최고조상, 모든 예외처리 가능
        
        ⇒ 맨 마지막에 배치해주는 것이 좋음
        
<br>

### 예외 정보들을 볼 수 있는 메서드

> 예외발생 → 예외 객체 생성 → 거기엔 예외에 대한 정보들이 있음(이 안에 메서드들 존재)
> 
- printStackTrace()
    - `예외발생 당시의 호출스택(call stack)에 있었던 메서드의 정보와 예외 메시지`를 화면에 출력
- getMessage()
    - `발생한 예외클래스의 인스턴스에 저장된 메시지`를 얻을 수 있다.

![image](https://user-images.githubusercontent.com/102898794/199236965-1258204d-50db-4356-a51b-531582edc389.png)
<br>

### 멀티 catch 블럭

: 내용이 같은 catch블럭을 하나로 합친 것(JDK1.7부터)

![image](https://user-images.githubusercontent.com/102898794/199237021-7860b226-ad98-4763-8fdb-10981c51b69b.png)


- 부모 자식 관계는 안됨
    - 부모만 써주면 되니까 불필요
- 참조변수로 사용할 수 있는 건 공통된 것만
    - 잘 안쓰지만 if로 공통되지 않은 것 쓸 수 있음
    
    ![image](https://user-images.githubusercontent.com/102898794/199237139-caa10e86-ae61-46a1-ae7d-4dc4e45736a4.png)
    
    ### 예외발생시키기
    
    ![image](https://user-images.githubusercontent.com/102898794/199237234-bc588a2e-48e0-4840-8832-0c5c9ed17f57.png)
    
<br>

### checked예외, unchecked예외

- checked예외
    - 컴파일러가 예외처리 여부를 체크(예외처리 필수)
    - exception과 자손
- unchecked예외
    - 컴파일러 예외처리 여부 체크 x(예외처리 선택)
    - runtimeexception과 자손
    
    - runtimeexception과 자손에 해당하는 클래스에 예외처리 필수 아닌이유
        - runtimeexception과 자손은 프로그래머의 실수로 발생
        - runtimeexception에 속하는 예외에도 예외처리를 해줘야한다면  사용되는 모든 곳에 예외처리를 해줘야하기때문에
<br>

## 2. 메서드 예외 선언하기

: 메서드가 호출시 발생가능한 예외를 호출하는 쪽에 알리는 것

- 메서드에 예외 선언
    - 메서드 선언부에 키워드 throws를 사용해서 메서드 내에서 발생할 수 있는 예외 적어 주면 된다
        - `throws + 필수처리예외만 선언 (체크드 예외)`
    - 예외가 여러개일 경우 쉼표(,)로 구분
        
        ![image](https://user-images.githubusercontent.com/102898794/199237441-19315550-9248-4494-8dca-66b578a1e683.png)
        
    - 모든 예외의 최고 조상 Exception클래스를 메서드에 선언하면,
        - 이 메서드는 모든 종류의 예외가 발생할 가능성이 있다는 뜻
    - 오버라이딩할 때 단순히 선언된 예외의 개수가 아니라 상속 관계까지 고려해줘야한다
        - 위의 경우 Exception클래스에 모두 포함되니까 Exception이 있을때 오버라이딩 못함
    - `예외를 발생시키는 throw`와  `예외를 메서드에 선언할 때쓰이는 throws` 구별 잘 하기!!
        
        ```java
        🐳 오버라이딩 조건
        1. 선언부 일치
        2. 접근제어자 좁게 x
        3. 조상보다 많은 에러선언 x
        
        ```
        
        ```java
        public static void main(String[] args) throws Exception {
        		method1();	 // 같은 클래스내의 static멤버이므로 객체생성없이 직접 호출가능.
          	}	// main메서드의 끝
        
        	static void method1() throws Exception {
        		method2();
        	}	// method1의 끝
        
        	static void method2() throws Exception {
        		throw new Exception();
        	}	// method2의 끝
        ```
        
        ![image](https://user-images.githubusercontent.com/102898794/199237645-973654f3-8615-4ed5-a49b-70f3722551a7.png)
        
        → 프로그램 실행도중 java,lang.Exception이 발생하여 비정상적으로 종료된것, 예외가 발생했을때 호출 스택의 내용을 알 수 있다.
        
        - 예외를 호출스택이 진행되면서 마지막에 main에 넘겨주게 되는데 ⇒ JVM에 넘김
        - main메서드에서 조차 예외처리를 해주지 않았으므로 main메서드가 종료되어 프로그램이 예외로 인해 비정상적으로 종료되는 것
            - **어느 한 곳에는 반드시 try-catch문으로 예외처리를 해줘야 한다**.
        - 예외가 선언되어 있으면 Exception과 같은 체크드 예외를 **try-catch문으로** 처리하지 않아도 컴파일 에러 발생 안함
<br>

### finally 블럭

- 예외 발생여부 상관없이 실행되어야할 코드를 포함시킬 목적(중복될 코드 제거)

![image](https://user-images.githubusercontent.com/102898794/199237824-e268b8b1-7ad2-444e-8a5c-c0160860376f.png)
<br>

### 사용자 정의 예외 만들기

- 우리가 직접 예외클래스 정의

![image](https://user-images.githubusercontent.com/102898794/199237936-7d00f272-ade9-410f-ac93-b1343420faf7.png)
<br>

### 예외 되던지기(exception re-throwing)

- 예외를 처리한 후에 다시 예외를 발생시키는 것
- 호출 메서드와 호출된 메서드 양쪽 모두에서 예외처리하는 것
    - 주의할 점
    - 예외가 발생할 메서드는 try-catch문을 사용해서 예외처리를 해줌과 동시에 메서드의 선언부에 발생할 예외를 throws에 지정해 줘야한다.
    
    ```java
    public static void main(String[] args) {
    		try  {
    			method1();		
    		} catch (Exception e)	{   //예외처리2
    			System.out.println("main메서드에서 예외가 처리되었습니다.");
    		}
    	}	// main메서드의 끝
    
    	static void method1() throws Exception {
    		try {
    			throw new Exception();
    		} catch (Exception e) {   //예외처리1
    			System.out.println("method1메서드에서 예외가 처리되었습니다.");
    			throw e;			// 다시 예외를 발생시킨다.
    		}
    	}	// method1메서드의 끝
    ```
<br>
    
### 연결된 예외(chained exception)
    
    - 한 예외가 다른 예외를 발생시킬 수 있다
    - 예외 A가 예외B를 발생시켰다면, A를 B의 ‘원인 예외(cause exception)’
    
  ![image](https://user-images.githubusercontent.com/102898794/199238157-16e1f09e-30b3-4e1d-85e1-7718cc54e1c5.png)
   

- 연결된  예외를 쓰는 이유
    1. 여러가지 예외를 하나의 큰 분류의 예외를 묶어서 다루기 위해서
        1. 하나씩 써주는 것보다 큰 분류로 묶어서 처리할때가 편할때 있음
            1. 상속으로 처리하면 상속관계도 변경해야하고 실제로 발생한 예외를 알 수 없다는 단점이 있음
    2. checked예외를 unchecked예외로 바꿀 수 있도록 하기위해서
    
![image](https://user-images.githubusercontent.com/102898794/199238238-85fe7c13-35a7-47a1-a2f4-12625868506a.png)
